// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9M3OBeOdQgaozaV4ePDBL6ZP3rP9fslk',
    appId: '1:908925798322:web:1d0582dce8923bdc0246ab',
    messagingSenderId: '908925798322',
    projectId: 'mobileprogramming-da8cf',
    authDomain: 'mobileprogramming-da8cf.firebaseapp.com',
    storageBucket: 'mobileprogramming-da8cf.appspot.com',
    measurementId: 'G-D4HEKHLQFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz-e7XwpaKs88d-WCDdIJ-SPLchXtF_8U',
    appId: '1:908925798322:android:fa8a12e16d0a90a50246ab',
    messagingSenderId: '908925798322',
    projectId: 'mobileprogramming-da8cf',
    storageBucket: 'mobileprogramming-da8cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFZP16nUIGRVBr5eo4c6jmf9hIDL3Fbks',
    appId: '1:908925798322:ios:536d1f9c12e36ad00246ab',
    messagingSenderId: '908925798322',
    projectId: 'mobileprogramming-da8cf',
    storageBucket: 'mobileprogramming-da8cf.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFZP16nUIGRVBr5eo4c6jmf9hIDL3Fbks',
    appId: '1:908925798322:ios:536d1f9c12e36ad00246ab',
    messagingSenderId: '908925798322',
    projectId: 'mobileprogramming-da8cf',
    storageBucket: 'mobileprogramming-da8cf.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9M3OBeOdQgaozaV4ePDBL6ZP3rP9fslk',
    appId: '1:908925798322:web:cfe49fa95881adf50246ab',
    messagingSenderId: '908925798322',
    projectId: 'mobileprogramming-da8cf',
    authDomain: 'mobileprogramming-da8cf.firebaseapp.com',
    storageBucket: 'mobileprogramming-da8cf.appspot.com',
    measurementId: 'G-CL6ESKTCZB',
  );

}